# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Google Developer Group Catania"
email: "main@gdgcatania.org"
description: "GDG Catania community"
baseurl: "/gdgcatania"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Google Developer Group Catania"
organizerAlternateName: "Google Developer Group Catania"
organizerDescription: "Community aperta e volontaria che crea progetti e condivide le esperienze sulla tecnologia di Google con passione"
organizerEmail: "main@gdgcatania.org"
organizerLogo: "/img/seo/gdg-catania-logo.png"
organizerLink: "http://gdgcatania.org/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, Catania"
twitterAccount: "@gdgcatania"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "Catania"
typeoutTextValues: '"", "Google Developer Group"'
typeoutFallback: "Google Developer Group"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Cosa si fa in un GDG?"
aboutBlock:
 - {title: "Networking", image: "networking.jpg", text: "Si comunica sia durante gli eventi, ma non solo, sulle tecnologie e metodologie Google." }
 - {title: "Learning", image: "workshop.jpg", text: "I GDG nascono con lo scopo di aumentare il livello delle competenze di sviluppatori e designer in merito alle tecnologie e metodologie Google." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1133", specialCharacter: "+", info: "Partecipanti", detail: "da tutta la Sicilia"}
 - {count: "350", specialCharacter: "+", info: "Membri", detail: " attivi negli ultimi 6 mesi "}
 - {count: "25", specialCharacter: "+", info: "Eventi", detail: "organizzati negli ultimi 6 mesi"}

# Latest News Block
latestNewsTitle: "Cos'è un Google Developer Group?"

# StaffGDG
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Main GDG Catania"
rockstarSpeakersButtonText: ""

# Foto Block
venueBlockTitle: "Foto"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueSmallImage4: "venue_4.jpg"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Iscriviti per restare aggiornato!"
subscribeAction: "https://gdgcatania.us-50.list-manage.com/subscribe/post?u=fb72f52c09a716847b7389a39&id=f723af0519"
subscribeInfo: "Join us!"

# Footer
socialLinks:
 - {link: "https://facebook.com/gdgcatania/", icon: "facebook"}
 - {link: "https://plus.google.com/118102220008611585984", icon: "google-plus"}
 - {link: "https://twitter.com/gdgcatania", icon: "twitter"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com/groups/chapter/118102220008611585984/", text: "GDG Catania"}
   - {link: "https://developers.google.com", text: "Google Developers"}
   - {link: "https://www.womentechmakers.com/", text: "Women Techmakers"}
 -
  title: "Contatti"
  links:
   - {link: "mailto:main@gdgcatania.org", text: "main@gdgcatania.org"}


# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."
